<?php

/**
 * @file
 * Hooks and constants for islandora_form_fieldpanel.
 */

use Drupal\Core\Render\Element;
use Drupal\Core\Form\FormStateInterface;

use Drupal\islandora_form_fieldpanel\Element\FieldPane;
use Drupal\islandora_form_fieldpanel\Element\FieldPanel;

/**
 * Constants.
 */
// @codingStandardsIgnoreStart
define('ISLANDORA_FORM_FIELDPANEL_THEME_FIELDPANEL', 'fieldpanel');
define('ISLANDORA_FORM_FIELDPANEL_THEME_FIELDPANE', 'fieldpane');
define('ISLANDORA_FORM_FIELDPANEL_PATH_MODULE', drupal_get_path('module', 'islandora_form_fieldpanel') . '/');
define('ISLANDORA_FORM_FIELDPANEL_PATH_INCLUDES', ISLANDORA_FORM_FIELDPANEL_PATH_MODULE . 'includes/');
define('ISLANDORA_FORM_FIELDPANEL_PATH_THEME', ISLANDORA_FORM_FIELDPANEL_PATH_MODULE . 'theme/');
define('ISLANDORA_FORM_FIELDPANEL_PATH_JS', ISLANDORA_FORM_FIELDPANEL_PATH_MODULE . 'js/');
define('ISLANDORA_FORM_FIELDPANEL_PATH_CSS', ISLANDORA_FORM_FIELDPANEL_PATH_MODULE . 'css/');
// @codingStandardsIgnoreEnd

/**
 * Implements hook_theme().
 */
function islandora_form_fieldpanel_theme($existing, $type, $theme, $path) {
  return [
    // Single Field Panel holds multiple field panes.
    ISLANDORA_FORM_FIELDPANEL_THEME_FIELDPANEL => [
      'render element' => 'element',
    ],
    // The content of a single fieldpane.
    ISLANDORA_FORM_FIELDPANEL_THEME_FIELDPANE => [
      'function' => 'theme_fieldpane',
      'render element' => 'element',
      'file' => 'includes/FieldPane.inc',
    ],
  ];
}

/**
 * Process the 'fieldpane' Element.
 *
 * @param array $element
 *   The element to be processed.
 * @param \Drupal\Core\Form\FormStateInterface $form_state
 *   The drupal form state.
 * @param array $complete_form
 *   The drupal form.
 *
 * @return array
 *   The processed element.
 */
function islandora_form_fieldpanel_fieldpane_process(array $element, FormStateInterface $form_state, array $complete_form = []) {
  $form_state->loadInclude('islandora_form_fieldpanel', 'inc', 'includes/FieldPane');
  return FieldPane::process($element, $form_state, $complete_form);
}

/**
 * Process the 'fieldpanel' Element.
 *
 * @param array $element
 *   The element to be processed.
 * @param \Drupal\Core\Form\FormStateInterface $form_state
 *   The drupal form state.
 * @param array $complete_form
 *   The drupal form.
 *
 * @return array
 *   The processed element.
 */
function islandora_form_fieldpanel_fieldpanel_process(array $element, FormStateInterface $form_state, array $complete_form = []) {
  return FieldPanel::process($element, $form_state, $complete_form);
}

/**
 * Implements hook_WIDGET_ajax_alter().
 */
function islandora_form_fieldpanel_form_element_fieldpanel_ajax_alter(FormElement $element, array &$form, FormStateInterface $form_state) {
  $triggering_element = $form_state->getTriggeringElement();
  $action = $triggering_element['#ajax']['params']['action'];
  switch ($action) {
    case 'add':
      islandora_form_fieldpanel_form_element_fieldpane_ajax_add($element, $form, $form_state);
      break;

    case 'delete':
      islandora_form_fieldpanel_form_element_fieldpane_ajax_delete($element, $form, $form_state);
      break;

    case 'move':
      islandora_form_fieldpanel_form_element_fieldpane_ajax_move($element, $form, $form_state);
      break;

  }
}

/**
 * Adds new field pane to panel.
 */
function islandora_form_fieldpanel_form_element_fieldpane_ajax_add(FormElement $element, array &$form, FormStateInterface $form_state) {
  $pane = $element->findElement($form_state->getTriggeringElement()['#ajax']['params']['child']);
  $new_pane = clone $pane;

  $each_function = function ($element) {
    // Set a FormElement to its default value.
    $set_to_default = function ($el) {
      $el->default_value = $el->getOriginalDefaultValue();
    };

    // Set this one...
    $set_to_default($element);

    if ($element->controls['#type'] == 'tags') {
      // ... and make child "tag" elements unique.
      // First, map 'em all to their defaults.
      array_map($set_to_default, $element->children);

      // Filter function: Only pass unique values.
      $child_filter = function ($child) {
        static $values = [];
        $value = $child->default_value;
        if (!in_array($value, $values)) {
          $values[] = $value;
          return TRUE;
        }
        return FALSE;
      };
      // Run the filter function.
      $element->children = array_filter($element->children, $child_filter);
    }
  };
  $new_pane->eachDecendant($each_function);

  $element->adopt($new_pane);
  $form[] = $new_pane->toArray();
}

/**
 * Removed field pane from panel.
 */
function islandora_form_fieldpanel_form_element_fieldpane_ajax_delete(FormElement $element, array &$form, FormStateInterface $form_state) {
  $pane = $element->findElement($form_state->getTriggeringElement()['#ajax']['params']['child']);
  $pane->orphan();
  foreach (Element::children($form) as $child) {
    if ($form[$child]['#hash'] == $pane->hash) {
      unset($form[$child]);
      break;
    }
  }
}

/**
 * Moves field panel to new position.
 */
function islandora_form_fieldpanel_form_element_fieldpane_ajax_move(FormElement $element, &$form, FormStateInterface $form_state) {
  $values = $form_state->getValues();
  $move_values = _islandora_form_fieldpanel_form_element_retrieve_move_values($values);

  // Deal with input form.
  $current_values = $form_state->getUserInput();
  $current_complete_form_values = &$form_state->getCompleteForm();
  foreach ($form_state->getTriggeringElement()['#parents'] as $value) {
    if ($value !== 'move-fieldpane' && $value !== 'move-up-fieldpane' && $value !== 'move-down-fieldpane' && $value !== 'move-op' && !is_int($value)) {
      $current_values = &$current_values[$value];
      $current_complete_form_values = &$current_complete_form_values[$value];
    }
  }

  $move_element = $current_values[intval($move_values['move-element'])];
  $current_values[intval($move_values['move-element'])] = $current_values[$move_values['move-position']];
  $current_values[$move_values['move-position']] = $move_element;
  $form_state->setUserInput($current_values);
}

/**
 * Retrieves move values from form state values.
 */
function _islandora_form_fieldpanel_form_element_retrieve_move_values($values) {
  foreach ($values as $key => $value) {
    if ($key === 'move-fieldpane') {
      return $value;
    }
    elseif (is_array($value)) {
      $move_values = _islandora_form_fieldpanel_form_element_retrieve_move_values($value);
      if (!empty($move_values)) {
        return $move_values;
      }
    }
  }
  return NULL;
}
